### ISSUE TITLE
Melhorias projeto

### ISSUE THREAD

**Issue by feijoes** [Gabryel3B/Honest-Dokkan#1]
Eai mano, tudo bem ? 
Estava dando uma olhada em algums projetos de dokkan e acabei me deparando com o seu.

Dei uma olhada no seu codigo do seu projeto (que esta pesado, 200mb de imagens quase)
E comento algumas melhorias que possan ser feitas

### Criar arquivos css globals, 
   Vejo que tem muito css duplicado em muitos arquivos , caso nao saiba , voce pode criar um arquivo css global `main.css` por exemplo, que tem todos os css que todos as paginas estao usando e com isso em cada html voce importa 
### Ordernar os arquivos
   Tenta dar uma organizada nos arquivos, ta tudo muito junto , pasta de pagina do lado de pasta de imagem, cria uma pasta imagens e sobe todas as pastas de imagens nela por exemplo

Voce sabe usar js ? Caso não saiba Recomendo aprender para dar um upgrade na pagina, como por exemplo adicionar [pagination](https://developers.google.com/search/docs/specialty/ecommerce/pagination-and-incremental-page-loading?hl=pt-br#:~:text=Pagina%C3%A7%C3%A3o%3A%20quando%20o%20usu%C3%A1rio%20clica,conjunto%20inicial%20de%20resultados%20exibidos.)

E recomendação no projeto usa a tag [details](https://www.w3schools.com/tags/tag_details.asp)  para mostrar os detalhes dos personagens , com isso diminui muito o tamanho da pagina
```html
<details>
  <summary>tag</summary>
   Texto 
</details>
```

Ultimo detalhe , tentei enviar mensagen para seu discord gabryelkkkj , mas a conta nao aceita solicitação de amizade

**Comment by Gabryel3B** [comment]
Opa mano
Acho que primeiramente obrigado pelas dicas de melhoria né, valeu demais, sério

Honestamente eu não achei que alguém ia encontrar o repositório tão cedo, então peço perdão pela bagunça kkkk 
Mas irei buscar deixar mais organizado sim

Comecei a ver um pouco de js, logo logo verei oq posso colocar na página

Eu tinha até esquecido que meu discord não aceitava pedido, mas já mudei lá
Se tu quiser, manda pedido que eu respondo assim que puder
